In [4]:
import Bio
from Bio import SeqIO
from Bio.Cluster import distancematrix

import numpy as np
import pandas as pd

In [8]:
data = np.array([[0, 1,  2,  3],
                 [4, 5,  6,  7],
                 [8, 9, 10, 11],
                 [1, 2,  3,  4]])
distancematrix(data)

[array([], dtype=float64),
 array([16.]),
 array([64., 16.]),
 array([ 1.,  9., 49.])]

In [18]:
data = np.array([[0, 0],
                 [3, 4],
                 [5, 6],
                 [1, 2]])
distancematrix(data, transpose=False, dist='e')

[array([], dtype=float64),
 array([12.5]),
 array([30.5,  4. ]),
 array([ 2.5,  4. , 16. ])]

In [13]:
np.array([[ 0., 16., 64., 1.], [16., 0., 16., 9.], [64., 16., 0., 49.], [ 1., 9., 49., 0.]])

array([[ 0., 16., 64.,  1.],
       [16.,  0., 16.,  9.],
       [64., 16.,  0., 49.],
       [ 1.,  9., 49.,  0.]])

In [4]:
with open("../data/staph/core_gene_alignment-narsa.fasta", "w") as output:
    for sequence in SeqIO.parse('../data/staph/core_gene_alignment-narsa.aln', 'fasta'):
        seq = Bio.Seq.Seq(sequence.seq._data.upper(), alphabet=Bio.Alphabet.Alphabet())
        record = Bio.SeqRecord.SeqRecord(seq, id=sequence.id, description='')
        SeqIO.write(record, output, "fasta")

In [5]:
with open("../data/staph/saureus_core_gene_alignment.fasta", "w") as output:
    for sequence in SeqIO.parse('../data/staph/saureus_core_gene_alignment.aln', 'fasta'):
        seq = Bio.Seq.Seq(sequence.seq._data.upper(), alphabet=Bio.Alphabet.Alphabet())
        record = Bio.SeqRecord.SeqRecord(seq, id=sequence.id, description='')
        SeqIO.write(record, output, "fasta")

In [6]:
with open("../data/staph/combined.fasta", "w") as output:
    for sequence in SeqIO.parse('../data/staph/core_gene_alignment-narsa.aln', 'fasta'):
        seq = Bio.Seq.Seq(sequence.seq._data.upper(), alphabet=Bio.Alphabet.Alphabet())
        record = Bio.SeqRecord.SeqRecord(seq, id=sequence.id, description='')
        SeqIO.write(record, output, "fasta")
    for sequence in SeqIO.parse('../data/staph/saureus_core_gene_alignment.aln', 'fasta'):
        seq = Bio.Seq.Seq(sequence.seq._data.upper(), alphabet=Bio.Alphabet.Alphabet())
        record = Bio.SeqRecord.SeqRecord(seq, id=sequence.id, description='')
        SeqIO.write(record, output, "fasta")

In [5]:
src = SeqIO.parse('../data/staph/combined.fasta', 'fasta')
data = [(records_pseudo.id, records_pseudo.seq._data) for records_pseudo in src]
seq = pd.DataFrame(data=data, columns=['id', 'sequence'])

In [6]:
seq

         id                                           sequence
0    NRS001  ATGAACATTTATGATGAATATAGAAGTTATTTAATAGAAGAACTGG...
1    NRS002  ----------------------------------------------...
2    NRS003  ATGAACATTTATGATGAATATAGAAGTTATTTAATAGAAGAACTGG...
3    NRS021  ATGAAAATTTATGATGAATATAGAAGTTATGTAATAGAAGAACTGG...
4    NRS022  ATGAACATTTATGATGAATATAGAAGTTATGTAATAGAAGAACTGG...
..      ...                                                ...
383  SR4152  ATGTTAGATTTTGAAAAACCACTTTTTGAAATTCGAAATAAAATTG...
384  SR4153  ATGTTAGATTTTGAAAAACCACTTTTTGAAATTCGAAATAAAATTG...
385  SR4155  ATGTTAGATTTTGAAAAACCACTTTTTGAAATTCGAAATAAAATTG...
386  SR4156  ATGTTAGATTTTGAAAAACCACTTTTTGAAATTCGAAATAAAATTG...
387  SR4187  ATGTTAGATTTTGAAAAACCACTTTTTGAAATTCGAAATAAAATTG...

[388 rows x 2 columns]

In [9]:
for id_ in seq.id:
    print(id_)

NRS001
NRS002
NRS003
NRS021
NRS022
NRS027
NRS029
NRS035
NRS036
NRS039
NRS049
NRS051
NRS054
NRS063
NRS064
NRS070
NRS071
NRS072
NRS073
NRS074
NRS079
NRS100
NRS102
NRS103
NRS104
NRS105
NRS106
NRS107
NRS108
NRS109
NRS110
NRS111
NRS112
NRS113
NRS114
NRS119
NRS145
NRS148
NRS149
NRS152
NRS157
NRS161
NRS162
NRS164
NRS167
NRS168
NRS169
NRS170
NRS172
NRS174
NRS175
NRS177
NRS178
NRS180
NRS182
NRS183
NRS185
NRS187
NRS188
NRS189
NRS191
NRS192
NRS194
NRS196
NRS198
NRS199
NRS201
NRS202
NRS203
NRS204
NRS205
NRS207
NRS209
NRS210
NRS211
NRS212
NRS213
NRS214
NRS215
NRS216
NRS217
NRS218
NRS219
NRS220
NRS222
NRS223
NRS224
NRS225
NRS226
NRS227
NRS230
NRS231
NRS232
NRS233
NRS235
NRS236
NRS237
NRS239
NRS240
NRS241
NRS242
NRS243
NRS245
NRS246
NRS247
NRS248
NRS249
NRS252
NRS253
NRS254
NRS255
NRS256
NRS259
NRS260
NRS262
NRS264
NRS265
NRS266
NRS268
NRS271
NRS272
NRS275
NRS383
NRS386
NRS387
107
109
115
1203158
120335
120337
120338
122VISA
123
126
2001013782
2002002614
2002038081
2003718535
2006734597
2006745535
217
221
312
407
504
506
834N
BCH-SA-01
BCH-SA-02
BCH-SA-03
BCH-SA-04
BCH-SA-05
BCH-SA-06
BCH-SA-07
BCH-SA-08
BCH-SA-09
BCH-SA-10
BCH-SA-11
BCH-SA-12
BCH-SA-13
BCH-SA-14
BCH-SA-15
CA105
CA11
CA26
CA39
CA436
CA541
CA544
CA545
CA598
CA9
CFBREBSa101
CFBREBSa102
CFBREBSa103
CFBREBSa104
CFBREBSa105
CFBREBSa108
CFBREBSa110
CFBREBSa112
CFBREBSa114
CFBREBSa116
CFBREBSa117
CFBREBSa118
CFBREBSa119
CFBREBSa121
CFBREBSa122
CFBREBSa123
CFBREBSa125
CFBREBSa126
CFBREBSa127
CFBREBSa129
CFBREBSa130
CFBREBSa131
CFBREBSa133
CFBREBSa135
CFBREBSa138
CFBRSa03
CFBRSa04
CFBRSa05
CFBRSa06
CFBRSa07
CFBRSa21
CFBRSa22
CFBRSa23
CFBRSa24
CFBRSa25
CFBRSa26
CFBRSa27
CFBRSa28
CFBRSa29
CFBRSa30
CFBRSa47
CFBRSa48
CFBRSa49
CFBRSa50
CFBRSa51
CFBRSa66A
CFBRSa66B
CFBRSa70
CFBRSa74
EUH13
EUH15
EUH25
GA12
GA15
GA231
GA27
GA48963
GA50245
GA50819
GA51254
GA53617
GA53649
GA984
Grady1
JE2
MN055
MN105
N315
NRS001
NRS002
NRS003
NRS021
NRS022
NRS027
NRS029
NRS035
NRS036
NRS039
NRS049
NRS051
NRS054
NRS063
NRS064
NRS070
NRS071
NRS072
NRS073
NRS074
NRS079
NRS100
NRS102
NRS103
NRS104
NRS105
NRS106
NRS108
NRS109
NRS110
NRS111
NRS112
NRS113
NRS114
NRS119
NRS145
NRS148
NRS149
NRS152
NRS157
NRS161
NRS162
NRS164
NRS167
NRS168
NRS169
NRS170
NRS172
NRS175
NRS177
NRS178
NRS180
NRS182
NRS183
NRS185
NRS187
NRS188
NRS189
NRS191
NRS192
NRS194
NRS196
NRS198
NRS199
NRS201
NRS202
NRS203
NRS204
NRS205
NRS207
NRS209
NRS210
NRS211
NRS212
NRS213
NRS214
NRS215
NRS216
NRS217
NRS218
NRS219
NRS220
NRS222
NRS224
NRS225
NRS226
NRS227
NRS230
NRS231
NRS232
NRS233
NRS235
NRS236
NRS237
NRS239
NRS240
NRS241
NRS242
NRS243
NRS245
NRS246
NRS247
NRS248
NRS249
NRS252
NRS253
NRS254
NRS255
NRS256
NRS259
NRS260
NRS262
NRS264
NRS265
NRS266
NRS268
NRS271
NRS272
NRS275
NRS383
NRS386
NRS387
NY224
NY341
NY356
NY360
NY417
NY439
NY593
SR1065
SR1129
SR1287
SR1746
SR2091
SR220
SR2609
SR2852
SR3569
SR3585
SR3732
SR3777
SR4035
SR4152
SR4153
SR4155
SR4156
SR4187

In [21]:
nrs001 = seq.query('id=="NRS001"')
nrs001

         id                                           sequence
0    NRS001  ATGAACATTTATGATGAATATAGAAGTTATTTAATAGAAGAACTGG...
241  NRS001  ATGTTAGATTTTGAAAAACCACTTTTTGAAATTCGAAATAAAATTG...

In [24]:
len(nrs001['sequence'][0]), len(nrs001['sequence'][241])

(983088, 910519)

In [27]:
seq.loc[seq['id']=='NRS001']

         id                                           sequence
0    NRS001  ATGAACATTTATGATGAATATAGAAGTTATTTAATAGAAGAACTGG...
241  NRS001  ATGTTAGATTTTGAAAAACCACTTTTTGAAATTCGAAATAAAATTG...